### ISSUE TITLE
Code review by Team 108 (The Mambas)

### ISSUE THREAD

**Issue by 8Bts** [ozovalihasan/enumerable#2]
- Change explicit block with an implicit block if it is not necessary
- Make your my_each to be able to work on hash

**Comment by ebeagusamuel** [comment]
- Make your my_each to be able to work on hash
- Used yield instead of proc

**Comment by ozovalihasan** [comment]
Thanks for your feedbacks @8Bts and @ebeagusamuel . The following changes are done;

- Explicit blocks are changed with implicit blocks if they are not necessary. So, yields are deleted, too.
- my_each is checked and any problem related to hash couldn't be found. It is working correctly with hashes help of to_a method
